# CD [install -> build -> test -> delivery]

name: CD

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm i

      - name: Build app
        run: npm run build

      - name: run tests
        run: npm run test:routes

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'chatgroup-rs621'
          heroku_email: 'rogeliosamuel621@gmail.com'
          remote_branch: main # <- Include this
